spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todoList_ver2?rewriteBatchedStatements=true&serverTimezone=Asia/Seoul
#    url: jdbc:mysql://localhost:3306/todoList_ver2
    username: root
    password: Lucid123!

#    hikari:
#      maximum-pool-size: 30

  sql:
    init:
      mode: never

logging:
  level:
    com.zaxxer: debug
